### ISSUE TITLE
Errors highlighting crash vim-miximazer

### ISSUE THREAD

**Issue by timsofteng** [natebosch/vim-lsc#397] opened 2021-02-09 17:48 UTC
Hello. I often use [maximizer](https://github.com/szw/vim-maximizer) plugin to zoom my windows. Unfortunately it chashes when vim-lsc highlight error.
Could you fix it please?
Thanks

**Comment by natebosch** [comment] 2021-02-09 21:35
Can you give the error message when this happens?

**Comment by timsofteng** [comment] 2021-02-10 01:22
> Can you give the error message when this happens?

I mean it just crash the layout. You can reproduce it by this steps:

1. Open few split windows and maximize one of them with vim-maximizer
2. Invoke error from vim-lsc (e.g. some wrong syntax).

When vim-lsc marks error place (it's red colour in my colourscheme) then maximisation of window turns off and layout looks weird.

I can make screencast if it can't be reproduced on your environment.

Thanks.

**Comment by natebosch** [comment] 2021-02-12 04:53
I tried installing that plugin and I can reproduce what you see, unfortunately I don't know if there is much way around it. The issue reproduces for me for any usage of `:windo`.  You can confirm by maximizing a window with the plugin and running `:windo echo bufnr()`.

I didn't see anything in the help docs for `maximizer` about this problem, nor anything on their issue tracker, although https://github.com/szw/vim-maximizer/issues/4 looks suspciously similar and I wouldn't be surprised if it's also because of `:windo`.

Prefereably this I think should be fixed with the maximizer plugin.

I will take a look at whether I could feasibly implement what I need without `:windo`. If that doesn't work the last resort might need to be give a way to disable diagnostic highlighting in any window outside of the current one.

**Comment by natebosch** [comment] 2021-02-12 05:15
It looks like I could feasibly implement highlighting without `:windo` in very recent versions of vim, but not in nvim. It looks like vim supports specifying the window ID for both `matchaddpos()` and` matchdelete()`, but curiously nvim omits the support for `matchdelete()`.

**Comment by timsofteng** [comment] 2021-02-12 09:12
> It looks like I could feasibly implement highlighting without `:windo` in very recent versions of vim, but not in nvim. It looks like vim supports specifying the window ID for both `matchaddpos()` and` matchdelete()`, but curiously nvim omits the support for `matchdelete()`.

Thanks!
I'm not sure that it will help but neovim's built-in lsp works correctly with maximizer and layout still works. You might take a look how it works and get the idea.

**Comment by natebosch** [comment] 2021-03-15 02:21
I don't know why wasn't aware of this earlier. I just found out that `win_execute` exists and does not trigger any bad behavior in that plugin.

**Closed** 2021-03-15 02:21 UTC
