### ISSUE TITLE
Ignore files / folders

### ISSUE THREAD

**Issue by soywod** [natebosch/vim-lsc#77] opened 2018-04-12 09:32 UTC
Is it a way to ignore files or folders (like `node_modules` or `vendor`) for LSClientFindImplementations and/or LSClientFindReferences ?

**Comment by natebosch** [comment] 2018-04-25 16:17
There isn't an existing way. I could potentially add some support.

I assume you'd not want `LSClientGoToDefinition` to ignore these folders?

We could maybe add support for adding arbitrary interceptors per call and a utility function to intercept and filter. The config would end up looking like:

```viml
let g:lsc_server_commands = {
    \  'filetype': { 'command': 'server_command'
    \    'response_hooks': {
    \      'textDocument/references': lsc#filterLocations({'exclude': ['node_modules/.*', 'vendor/.*']}),
    \      'textDocument/implementation': lsc#filterLocations({'exclude': ['node_modules/.*', 'vendor/.*']}),
    \    }
    \ }
    \}
```

It's a little noisy but we could either add some utilities to reduce the noise or hide this in a plugin specific to the server you are configuring.

**Comment by natebosch** [comment] 2018-04-26 04:16
Could you try the branch `response_hooks` (https://github.com/natebosch/vim-lsc/pull/81) and let me know if it works for you?

I added a shortcut for the configuration to use the same filter for both references and implementations:

```viml
let g:lsc_server_commands = {
    \  'filetype': { 'command': 'server_command'
    \    'response_hooks': lsc#filterReferenceCalls({'exclude': ['node_modules/', 'vendor/']})
    \ }
    \}
```

**Comment by soywod** [comment] 2018-05-10 09:18
I switched to `response_hooks` branch and updated my vim conf with : 

```vim
let g:lsc_server_commands = {
  \ 'javascript.jsx': {
    \ 'command': 'node_modules/.bin/javascript-typescript-stdio',
    \ 'response_hooks': lsc#filterReferenceCalls({'exclude': ['node_modules/']})
    \ }
  \ }
```
but it still searches in `node_modules`, any idea ?

**Comment by soywod** [comment] 2018-05-15 16:28
Some more informations : 

I switched to branch `response_hooks`:

![image](https://user-images.githubusercontent.com/10437171/40069979-12a234bc-586d-11e8-97f5-5846908f8611.png)

I put this in my `.vimrc`:

```vim
let g:lsc_server_commands = {
  \ 'javascript': {
  \   'command': 'node_modules/.bin/javascript-typescript-stdio',
  \   'response_hooks': lsc#filterReferenceCalls({'exclude': ['node_modules/']})
  \   }
  \ }
```

In a regular `.js(x)` file it still searches in `node_modules`:

![ezgif com-optimize 1](https://user-images.githubusercontent.com/10437171/40069918-e7a0088e-586c-11e8-91b9-d4ff2b29f3dd.gif)

But in a regular `.ts(x)` file I don't have this problem (thanks to `tsconfig.json` I guess).

I hope these informations will help you.

**Comment by natebosch** [comment] 2018-05-29 05:33
ah, so the issue is that the server is doing the searching (and sending warnings about reading the files?). The issue is not that the quickfix list has too many entries in these directories?

I'm afraid there isn't anything the client side can do to prevent the server from reading those files. There might be some other configuration you can use. Looks like perhaps `jsconfig.json` is analogous to `tsconfig.json`?

https://github.com/sourcegraph/javascript-typescript-langserver/issues/394#issuecomment-372826241

**Comment by natebosch** [comment] 2018-11-18 19:09
Closing since I'm pretty sure this needs to be solved on the server configuration and the protocol doesn't give us a way to control it from the client.

**Closed by natebosch** 2018-11-18 19:09 UTC

**Comment by natebosch** [comment] 2019-04-09 23:33
All we can do on the client side is ignore work that the server does if it comes back with renames into those directories - we can't prevent the server from doing the work.

This would still need to be handled with a server configuration. If the server _does_ support such a configuration and we need to send it in `initializationOptions` then https://github.com/natebosch/vim-lsc/issues/132 could improve the UX, but it wouldn't solve anything that isn't possible today.
