### ISSUE TITLE
Completion stop working after getting empty items array from lsp server

### ISSUE THREAD

**Issue by sivakov512** [natebosch/vim-lsc#184] opened 2019-05-07 12:32 UTC
For example I have this code
```python
import pytest

pytestmark = [pytest.]  # cursor after pytest.
```
All is weel if I type `m` and trigger completion than - I will get all possible options.
If I type `mm`, trigger completion (got nothing), than remove one `m` and trigger completion than nothing works - completion stop working in any place of current file.

**Comment by natebosch** [comment] 2019-05-23 21:59
I wonder if this is a server issue? I can't reproduce this after making a request that returns 0 completions...

**Comment by sivakov512** [comment] 2019-05-24 04:21
I'am not sure about server issue, in logs I see that client stop sending request to server. But all is well if I type <C-n> and then trigger completion, for example.

In the provided logs you can see that there is no requests after line 13 of `in.log`, but I trigger completion many times.

in.log
```
Content-Length: 522

{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///home/sivakov512","capabilities":{"workspace":{"applyEdit":true},"textDocument":{"completion":{"completionItem":{"snippetSupport":false}},"synchronization":{"willSaveWaitUntil":false,"willSave":false,"didSave":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","source"]}}},"signatureHelp":{"dynamicRegistration":false},"definition":{"dynamicRegistration":false}}},"processId":21189,"trace":"off"}}Content-Length: 52

{"method":"initialized","jsonrpc":"2.0","params":{}}Content-Length: 163

{"method":"textDocument/didOpen","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py","version":1,"languageId":"python","text":""}}}Content-Length: 172

{"method":"textDocument/documentHighlight","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py"},"position":{"character":0,"line":0}}}Content-Length: 273

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"text":"def a():\n    prinn","rangeLength":0}],"textDocument":{"uri":"file:///home/sivakov512/sample.py","version":2}}}Content-Length: 165

{"method":"textDocument/completion","jsonrpc":"2.0","id":3,"params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py"},"position":{"character":9,"line":1}}}Content-Length: 172

{"method":"textDocument/documentHighlight","jsonrpc":"2.0","id":4,"params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py"},"position":{"character":8,"line":1}}}Content-Length: 254

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"range":{"end":{"character":9,"line":1},"start":{"character":8,"line":1}},"text":"","rangeLength":1}],"textDocument":{"uri":"file:///home/sivakov512/sample.py","version":3}}}Content-Length: 254

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"range":{"end":{"character":8,"line":1},"start":{"character":6,"line":1}},"text":"","rangeLength":2}],"textDocument":{"uri":"file:///home/sivakov512/sample.py","version":4}}}Content-Length: 172

{"method":"textDocument/documentHighlight","jsonrpc":"2.0","id":5,"params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py"},"position":{"character":5,"line":1}}}Content-Length: 120

{"method":"textDocument/didClose","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///home/sivakov512/sample.py"}}}Content-Length: 44

{"method":"shutdown","jsonrpc":"2.0","id":6}
```

out.log
```
Content-Length: 605
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 1, "result": {"capabilities": {"codeActionProvider": true, "codeLensProvider": {"resolveProvider": false}, "completionProvider": {"resolveProvider": false, "triggerCharacters": ["."]}, "documentFormattingProvider": true, "documentHighlightProvider": true, "documentRangeFormattingProvider": true, "documentSymbolProvider": true, "definitionProvider": true, "executeCommandProvider": {"commands": []}, "hoverProvider": true, "referencesProvider": true, "renameProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "experimental": {}}}}Content-Length: 43
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 2, "result": null}Content-Length: 138
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///home/sivakov512/sample.py", "diagnostics": []}}Content-Length: 75
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 3, "result": {"isIncomplete": false, "items": []}}Content-Length: 138
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///home/sivakov512/sample.py", "diagnostics": []}}Content-Length: 137
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 4, "result": [{"range": {"start": {"line": 1, "character": 4}, "end": {"line": 1, "character": 9}}, "kind": 2}]}Content-Length: 138
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///home/sivakov512/sample.py", "diagnostics": []}}Content-Length: 138
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///home/sivakov512/sample.py", "diagnostics": []}}Content-Length: 137
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc": "2.0", "id": 5, "result": [{"range": {"start": {"line": 1, "character": 4}, "end": {"line": 1, "character": 6}}, "kind": 2}]}
```

**Comment by sivakov512** [comment] 2019-05-24 04:23
I can reproduce this only with pyls, I use it like [this](https://github.com/sivakov512/.vim/blob/e7f4f73a8568c09162cc9c3aa419f576a8b02108/vimrc#L69).

**Comment by sivakov512** [comment] 2019-07-17 05:28
Any news here?

**Comment by natebosch** [comment] 2019-07-26 23:18
I'm unable to repro, here are the steps I took:

- Install `pyls` and `pytest` with `pip3`
- Configure to use `pyls` for python, as well as using `omnifunc` and disabling autocomplete.
- Write a file with the contents you have above.
- When I have my cursor following `pytest.m` and complete with `omnifunc` I get `.main(` and `.mark` as suggestions.
- Hit `<c-n>` twice to accept neither
- Type another `m` so my cursor now follows `pytest.mm`.
- Complete with `omnifunc`, no suggestions pop up.
- Delete one `m` so my cursor now follows `pytest.m` again
- Complete with `omnifunc` and get the same 2 suggestions as I got previously...

`pip3 show python-language-server` shows:

```
Name: python-language-server
Version: 0.28.0
Summary: Python Language Server for the Language Server Protocol
Home-page: https://github.com/palantir/python-language-server
Author: Palantir Technologies, Inc.
Author-email: None
License: UNKNOWN
Location: /Users/nbosch/.brew/lib/python3.7/site-packages
Requires: python-jsonrpc-server, pluggy, future, jedi
Required-by:
```

**Comment by natebosch** [comment] 2019-07-26 23:22
I wonder if we can narrow down the reasons we might not send a completion request:

If `b:lsc_completion` exists still we won't send a request:
https://github.com/natebosch/vim-lsc/blob/c491351fcfdb58d36da739912701d7132a33110e/autoload/lsc/complete.vim#L153

Can you check if that variable exists when you are in the state where it stops working?

We only unlet that on `CompleteDone` so I wonder if something in your config is making that autocommand not fire?

https://github.com/natebosch/vim-lsc/blob/c491351fcfdb58d36da739912701d7132a33110e/autoload/lsc/complete.vim#L66

**Comment by sivakov512** [comment] 2019-07-31 05:15
> Can you check if that variable exists when you are in the state where it stops working?

I check it now in case when completion stop working with `:echo exists('b:lsc_completion')` and it returns `1`.

> We only unlet that on CompleteDone so I wonder if something in your config is making that autocommand not fire?
Not sure, because I can't write hard things with viml =) You can look at my vimrc [here](https://github.com/sivakov512/.vim/blob/master/vimrc)

**Comment by sivakov512** [comment] 2019-07-31 05:16
I should mention that I can reproduce this problem with Rust also

**Comment by natebosch** [comment] 2019-07-31 19:52
@sivakov512 - can you try the branch in https://github.com/natebosch/vim-lsc/pull/198 and see if it resolves this for you?

What version of vim are you using, I wonder if there is a bug or difference in the way the `CompleteDone` autocmd works...

**Comment by sivakov512** [comment] 2019-08-02 04:11
Wow, works well!

vim --version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 09:06:19)
Included patches: 1-1764
Compiled by void-buildslave@a-hel-fi
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             +xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        -mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: cc -c -I. -Iproto -DHAVE_CONFIG_H     -fstack-clash-protection -mtune=generic -O2 -pipe   -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: cc   -L. -Wl,-z,relro -Wl,-z,now     -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now     -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl   -lncursesw -lacl -lattr -ldl  -L/usr/lib -llua -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -pthread  -L/usr/lib/perl5/core_perl/CORE -lperl -lm -lcrypt -lpthread -ldl  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lruby -lm
```

**Comment by natebosch** [comment] 2019-08-02 18:53
Merged to master

**Closed** 2019-08-02 18:53 UTC
