### ISSUE TITLE
Error echos to below statusline on hover

### ISSUE THREAD

**Issue by rislah** [natebosch/vim-lsc#219] opened 2019-10-19 22:05 UTC
When I hover over a error, it echos the error to below the statusline. I'm unable to open the location list with one command, as it prompts me "Press ENTER or type command to continue". Its in general clutter and I wish to disable it. Apologies if it's not vim-lsc specific, but I couldn't find any information on it.

**Comment by natebosch** [comment] 2019-10-24 00:08
To make sure I understand, do you see the "Press ENTER" prompt come up while moving around in the file?

Do you have an example error where this happens, and maybe a screenshot?

We've had this kind of trouble in the past, I _thought_ I had resolved it all and gotten it so the message always fits in one line. Most recently in https://github.com/natebosch/vim-lsc/pull/204

Do you have a custom ruler format?

I'm not sure I understand how this prevents you from opening the location list. Can you elaborate?

**Comment by rislah** [comment] 2019-10-24 01:18
> To make sure I understand, do you see the "Press ENTER" prompt come up while moving around in the file?

No. When I open any window that comes up as a popup. Help manual, location list, quickfix etc. It always prompts before opening and before closing. It only happens when my cursor is placed on a vim-lsc error.

The prompt I'm getting: https://i.imgur.com/mcr44Ww.png.



> Do you have a custom ruler format?

No rulerformat

**Comment by pwntester** [comment] 2019-10-28 09:31
Im getting the same issue. It seems to happen when cursor is over a line with a diagnostic and window is changed

**Comment by natebosch** [comment] 2019-10-29 03:47
Ah, I think this was due to an errant `echo` I left from debugging another feature.

I _think_ this should be fixed by https://github.com/natebosch/vim-lsc/commit/730d901164497f17b15a42d531b346752cc10765

Please reopen if this is still a problem after updating to the latest.

**Closed by natebosch** 2019-10-29 03:47 UTC

**Comment by pwntester** [comment] 2019-10-29 14:39
Thanks, cant reproduce the issue anymore
